-- tests/backward_forward_spec.lua
-- Unit tests for BackwardForward.nvim

local bf = require("backward-forward")

describe("backward-forward", function()
  before_each(function()
    vim.cmd("silent! %bwipeout!")
    bf._reset()
  end)

  describe("can_go_back", function()
    it("returns false with empty history", function()
      assert.is_false(bf.can_go_back())
    end)

    it("returns true after recording multiple positions", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_name(buf, "/tmp/test_bf_1.lua")
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      bf._record(true)
      assert.is_true(bf.can_go_back())
    end)
  end)

  describe("can_go_forward", function()
    it("returns false with empty history", function()
      assert.is_false(bf.can_go_forward())
    end)

    it("returns true after going back", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_name(buf, "/tmp/test_bf_2.lua")
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      bf._record(true)
      bf.go_back()
      assert.is_true(bf.can_go_forward())
    end)
  end)

  describe("go_back", function()
    it("does not error when history is empty", function()
      assert.has_no.errors(function()
        bf.go_back()
      end)
    end)

    it("moves cursor to previous position", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_name(buf, "/tmp/test_bf_3.lua")
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)
      vim.api.nvim_win_set_cursor(0, { 30, 0 })
      bf._record(true)
      bf.go_back()
      local pos = vim.api.nvim_win_get_cursor(0)
      assert.equals(1, pos[1])
    end)

    it("navigates across buffers", function()
      local buf1 = vim.api.nvim_create_buf(true, false)
      local buf2 = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_buf_set_name(buf1, "/tmp/test_bf_4a.lua")
      vim.api.nvim_buf_set_name(buf2, "/tmp/test_bf_4b.lua")
      vim.api.nvim_buf_set_lines(buf1, 0, -1, false, { "buf1" })
      vim.api.nvim_buf_set_lines(buf2, 0, -1, false, { "buf2" })

      vim.api.nvim_set_current_buf(buf1)
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)

      vim.api.nvim_set_current_buf(buf2)
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)

      bf.go_back()
      assert.equals(buf1, vim.api.nvim_get_current_buf())
    end)
  end)

  describe("go_forward", function()
    it("does not error when history is empty", function()
      assert.has_no.errors(function()
        bf.go_forward()
      end)
    end)

    it("moves cursor to next position after go_back", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_name(buf, "/tmp/test_bf_5.lua")
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)
      vim.api.nvim_win_set_cursor(0, { 30, 0 })
      bf._record(true)
      bf.go_back()
      bf.go_forward()
      local pos = vim.api.nvim_win_get_cursor(0)
      assert.equals(30, pos[1])
    end)
  end)

  describe("back-forward stability", function()
    it("does not get stuck oscillating", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_name(buf, "/tmp/test_bf_6.lua")
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))

      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      bf._record(true)
      vim.api.nvim_win_set_cursor(0, { 40, 0 })
      bf._record(true)

      bf.go_back()
      assert.equals(20, vim.api.nvim_win_get_cursor(0)[1])
      bf.go_back()
      assert.equals(1, vim.api.nvim_win_get_cursor(0)[1])
      bf.go_forward()
      assert.equals(20, vim.api.nvim_win_get_cursor(0)[1])
      bf.go_forward()
      assert.equals(40, vim.api.nvim_win_get_cursor(0)[1])
    end)

    it("truncates forward history on new navigation", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_name(buf, "/tmp/test_bf_7.lua")
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))

      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      bf._record(true)
      vim.api.nvim_win_set_cursor(0, { 40, 0 })
      bf._record(true)

      bf.go_back()
      vim.api.nvim_win_set_cursor(0, { 35, 0 })
      bf._record(true)

      assert.is_false(bf.can_go_forward())
      local state = bf._get_state()
      assert.equals(3, #state.history)
    end)
  end)

  describe("_record", function()
    it("deduplicates same file+line", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_name(buf, "/tmp/test_bf_8.lua")
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "line1" })
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)
      bf._record(true)
      bf._record(true)
      local state = bf._get_state()
      assert.equals(1, #state.history)
    end)

    it("skips small jumps when not forced", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_name(buf, "/tmp/test_bf_9.lua")
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)
      vim.api.nvim_win_set_cursor(0, { 5, 0 })
      bf._record(false)
      local state = bf._get_state()
      assert.equals(1, #state.history)
    end)

    it("records large jumps", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_name(buf, "/tmp/test_bf_10.lua")
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 50))
      vim.api.nvim_win_set_cursor(0, { 1, 0 })
      bf._record(true)
      vim.api.nvim_win_set_cursor(0, { 20, 0 })
      bf._record(false)
      local state = bf._get_state()
      assert.equals(2, #state.history)
    end)

    it("skips non-file buffers", function()
      local buf = vim.api.nvim_create_buf(false, true)
      vim.api.nvim_set_current_buf(buf)
      vim.bo[buf].buftype = "nofile"
      bf._record(true)
      local state = bf._get_state()
      assert.equals(0, #state.history)
    end)

    it("respects max_history limit", function()
      local buf = vim.api.nvim_create_buf(true, false)
      vim.api.nvim_set_current_buf(buf)
      vim.api.nvim_buf_set_name(buf, "/tmp/test_bf_11.lua")
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.fn["repeat"]({ "line" }, 200))
      for i = 1, 110 do
        vim.api.nvim_win_set_cursor(0, { math.min(i, 200), 0 })
        bf._record(true)
      end
      local state = bf._get_state()
      assert.is_true(#state.history <= 100)
    end)
  end)

  describe("get_bufferline_components", function()
    it("returns two components with correct text", function()
      local components = bf.get_bufferline_components()
      assert.equals(2, #components)
      assert.equals(" ◀ ", components[1].text)
      assert.equals(" ▶ ", components[2].text)
    end)

    it("uses inactive highlight when history is empty", function()
      local components = bf.get_bufferline_components()
      assert.equals("BackwardForwardInactive", components[1].link)
      assert.equals("BackwardForwardInactive", components[2].link)
    end)
  end)

  describe("setup", function()
    it("does nothing when enabled is false", function()
      assert.has_no.errors(function()
        bf.setup({ enabled = false })
      end)
    end)

    it("registers mouse mappings when mouse_buttons is true", function()
      bf.setup({ mouse_buttons = true })
      local maps = vim.api.nvim_get_keymap("n")
      local found_x1 = false
      local found_x2 = false
      for _, m in ipairs(maps) do
        if m.lhs == "<X1Mouse>" then found_x1 = true end
        if m.lhs == "<X2Mouse>" then found_x2 = true end
      end
      assert.is_true(found_x1, "X1Mouse mapping should be registered")
      assert.is_true(found_x2, "X2Mouse mapping should be registered")
    end)

    it("registers user commands", function()
      bf.setup({})
      local cmds = vim.api.nvim_get_commands({})
      assert.is_not_nil(cmds["NavigateBack"])
      assert.is_not_nil(cmds["NavigateForward"])
    end)
  end)
end)
